#ifndef WORD_COMPRESSION_CODES_DEFINED
#define WORD_COMPRESSION_CODES_DEFINED 1

#define WORD_COMPRESSION_ERROR_SPACE(code) ((0xcc + code) * -1)

#define WORD_COMPRESSION_ERROR_NULL_POINTER WORD_COMPRESSION_ERROR_SPACE(9)
#define WORD_COMPRESSION_ERROR_MISSING_ARGUMENTS WORD_COMPRESSION_ERROR_SPACE(8)
#define WORD_COMPRESSION_ERROR_STDIO WORD_COMPRESSION_ERROR_SPACE(7)
#define WORD_COMPRESSION_ERROR_LOGICAL WORD_COMPRESSION_ERROR_SPACE(6)
#define WORD_COMPRESSION_ERROR_CORRUPTION WORD_COMPRESSION_ERROR_SPACE(5)
#define WORD_COMPRESSION_ERROR_EMPTY_POSITION WORD_COMPRESSION_ERROR_SPACE(4)
#define WORD_COMPRESSION_ERROR_ENCODE WORD_COMPRESSION_ERROR_SPACE(3)
#define WORD_COMPRESSION_ERROR_SIZE WORD_COMPRESSION_ERROR_SPACE(2)
#define WORD_COMPRESSION_ERROR_ALLOC WORD_COMPRESSION_ERROR_SPACE(1)

#define WORD_COMPRESSION_SUCCESS 0

#include <time.h>

char *word_compression_last_error();
short word_compression_error(short, char *, ...);
time_t word_compression_last_error_time();
short word_compression_last_error_code();

#endif