
#define WORD_COMPRESSION_MAJOR_VER 1
#define WORD_COMPRESSION_MINOR_VER 0
#define WORD_COMPRESSION_SUBMINOR_VER 0

#ifndef WORD_COMPRESSOR_SHOW_VERSION_DEFINED
#define WORD_COMPRESSOR_SHOW_VERSION_DEFINED 1

const char *word_compression_version();

#endif